const mockEvents = {
  city: {
    id: 1007700,
    city: 'München',
    lat: 48.14,
    lon: 11.58,
    state: '',
    country: 'de',
    zip: 'meetup3',
    member_count: 1257
  },
  events: [
    {
      created: 1552577540000,
      duration: 7200000,
      id: '259762490',
      name: 'Rust libp2p',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1556812800000,
      local_date: '2019-05-02',
      local_time: '18:00',
      updated: 1553270253000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 14,
      venue: {
        id: 26268777,
        name: 'Instana - WeWork',
        lat: 48.14487838745117,
        lon: 11.576659202575684,
        repinned: true,
        address_1: 'Oskar-von-Miller-Ring 20',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1532692208000,
        name: 'Munich IPFS',
        id: 29367386,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munich-IPFS-User-Group',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Munich-IPFS-User-Group/events/259762490/',
      description: '<p>(This event is co-organized with the Rust User Group: <a href="https://www.meetup.com/de-DE/rust-munich/events/259984522/" class="linkified">https://www.meetup.com/de-DE/rust-munich/events/259984522/</a>)</p> <p>IPFS is meant to be not just a number of programs from protocol labs, but a set of cleanly specified open protocols that can be implemented in many different languages for everybody that needs a peer to peer networking stack to write p2p applications.</p> <p>Pierre Krieger, also known as tomaka on github and twitter, is going to talk about the rust implementation of libp2p that is being developed for parity.io.</p> ',
      visibility: 'public'
    },
    {
      created: 1554280915000,
      duration: 7200000,
      id: '260303680',
      name: 'Technology Radar Vol. 20 Presentation',
      rsvp_limit: 106,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1557248400000,
      local_date: '2019-05-07',
      local_time: '19:00',
      updated: 1555516043000,
      utc_offset: 7200000,
      waitlist_count: 22,
      yes_rsvp_count: 106,
      venue: {
        id: 25852478,
        name: 'ThoughtWorks Munich ',
        lat: 48.135860443115234,
        lon: 11.613353729248047,
        repinned: true,
        address_1: 'Bothestraße 11',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1413448074000,
        name: 'ThoughtWorks Munich',
        id: 17658472,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'ThoughtWorks-Muenchen',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/ThoughtWorks-Muenchen/events/260303680/',
      description: '<p>*** Registrations via our website ***<br/><a href="https://thoughtworks.com/technology_radar_de" class="linkified">https://thoughtworks.com/technology_radar_de</a></p> <p>Adopt, trial, assess or hold?<br/>Get ahead of the latest technology trends.</p> <p>The Technology Radar, based on our observations, conversations and experiences with our customers, covers both existing and emerging technologies.</p> <p>The report divides the trends into four groups: Techniques, platforms, tools, programming languages and frameworks. Within these groups, each trend has a recommendation: "Hold" for technologies that are not initially recommended for use; "Assess" for technologies that require further evaluation; "Trial" for technologies that are ready for use; and "Adopt" for mature technologies.</p> <p>Learn more about the latest technology and join us for the event in our Munich office.</p> <p>We are looking forward to welcome you!</p> <p>Agenda:</p> <p>18:30 - 19:00 Registration and Drinks</p> <p>19:00 - 20:30 Technology Radar Presentation (incl. Q&amp;A)</p> <p>20:30 - 22:00 Get Together with drinks &amp; fingerfood</p> <p>The presentation will be held in English.</p> <p>---</p> <p>*** Registrierung über unsere Website ***<br/><a href="https://thoughtworks.com/de/technology_radar_de" class="linkified">https://thoughtworks.com/de/technology_radar_de</a></p> <p>Adopt, trial, assess oder hold?<br/>Erfahre von unseren Experten mehr zu den neuesten Technologietrends.</p> <p>Der Technology Radar, der auf unseren Beobachtungen, Gesprächen und Erfahrungen mit unseren Kunden beruht, behandelt sowohl existierende als auch neu aufkommende Technologien.</p> <p>Der Report teilt die Trends in vier Gruppen auf: Techniken, Plattformen, Tools sowie Programmiersprachen und Frameworks. Innerhalb dieser Gruppen wird jeder Trend mit einer Empfehlung versehen: „Hold“ für Technologien, von deren Verwendung vorerst abgeraten wird; „Assess“ für Technologien, die einer weiteren Evaluation bedürfen; „Trial“ für Technologien, die einsatzbereit sind und „Adopt“ für ausgereifte Technologien.</p> <p>Erfahre mehr über die neusten Technologietrends und melde dich für unsere Technology Radar Präsentation in München an.</p> <p>Wir freuen uns auf dich!</p> <p>Agenda:</p> <p>18:30 - 19:00 Registrierung und Drinks</p> <p>19:00 - 20:30 Technology Radar Präsentation (inkl. Q&amp;A)</p> <p>20:30 - 22:00 Get Together mit Drinks &amp; Fingerfood</p> <p>Die Präsentation findet auf Englisch statt.</p> ',
      visibility: 'public'
    },
    {
      created: 1553601323000,
      duration: 25200000,
      id: '260079692',
      name: 'Kotlin Saturday Workshop',
      rsvp_limit: 25,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1556355600000,
      local_date: '2019-04-27',
      local_time: '11:00',
      updated: 1554301095000,
      utc_offset: 7200000,
      waitlist_count: 41,
      yes_rsvp_count: 25,
      venue: {
        id: 26244427,
        name: 'JetBrains GmbH',
        lat: 48.13737487792969,
        lon: 11.52295970916748,
        repinned: true,
        address_1: 'Elsenheimerstraße 49',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1421043158000,
        name: 'Kotlin User Group Munich - KUG Munich',
        id: 18325305,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Kotlin-User-Group-Munich',
        who: 'KUG-Hacker',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Kotlin-User-Group-Munich/events/260079692/',
      description: '<p>Do you want to learn Kotlin, but don’t know where to start?<br/>Here’s the deal.<br/>We will have a Kotlin Workshop on April 27th, from 11.00 in the Munich office!</p> <p>We will start with a live coding introduction into the basics of the Kotlin language. We will discuss in depth the features of the language and cover fluent APIs, higher-order functions, lambdas, and type-safe DSLs. You’ll be able to see how these language features are used in real life examples. You will get an understanding of the magic behind type-safe builders. Kotlin Coroutines will be covered next, where you will be able to explain afterwards why Coroutines are not threads, not Fibers. You’ll learn how ‘suspend’ functions are used to simplify callback driven programming and how they can help you to turn callback-style code into linear looking code. With Kotlin you can compile your code for JVM, Android, iOS, Mac, and JS. With multiplatform projects, you may easily reuse your Kotlin code across different platforms. Logic, business rules, utilities, and RPC are all good examples of possible code parts you should reuse. You’ll see how Kotlin code can be used in React frontend, JVM backend, Android and iOS, and Native. Let\'s have some fun!</p> <p>This Kotlin Workshop will take place on April 27th, from 11.00 to 18.00 at JetBrains Event Space in Munich. Please bring with you a laptop with IntelliJ IDEA installed and a charger; there are going to be a few hands-on exercises.</p> ',
      visibility: 'public'
    },
    {
      created: 1554728176000,
      duration: 10800000,
      id: '260445923',
      name: 'Kotlin Users Group Meetup May',
      rsvp_limit: 90,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1557161100000,
      local_date: '2019-05-06',
      local_time: '18:45',
      rsvp_close_offset: 'PT44H',
      updated: 1554978288000,
      utc_offset: 7200000,
      waitlist_count: 26,
      yes_rsvp_count: 90,
      venue: {
        id: 26112492,
        name: 'Google',
        lat: 48.143035888671875,
        lon: 11.541084289550781,
        repinned: true,
        address_1: 'Erika-Mann-Straße 33',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1421043158000,
        name: 'Kotlin User Group Munich - KUG Munich',
        id: 18325305,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Kotlin-User-Group-Munich',
        who: 'KUG-Hacker',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Kotlin-User-Group-Munich/events/260445923/',
      description: '<p>Hello Kotliners. Join us in our May gathering at Google office.</p> <p>Agenda:</p> <p>19:00 - Opening doors</p> <p>19:15 - Michal Harakal - Kotlin multiplatform roller-coaster ride or how I\'ve rewritten a conference app over the weekend.</p> <p>19.55 - Shagen Ogandzhanian (JetBrains) - Kotlin and JS interop, what\'s next. How to use javascript libraries in Kotlin world</p> <p>20.30 - Leonid Popescu (Payworks) - Hybrid SDKs or how we started with Kotlin/Multiplatform without trashing the existing code base</p> <p>Have you been working on a project with Kotlin? Is there a library you would like to discuss? Do you want to try public speaking?<br/>Message us, come and have fun sharing your Kotlin story!</p> ',
      how_to_find_us: 'We will need the full list of guests to print badges beforehand. RSVP will be closed a few days before to implement it.',
      visibility: 'public'
    },
    {
      created: 1554313880000,
      duration: 10800000,
      id: '260314997',
      name: 'Exceptions Demystified',
      rsvp_limit: 200,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1556211600000,
      local_date: '2019-04-25',
      local_time: '19:00',
      rsvp_open_offset: 'PT336H',
      updated: 1556120190000,
      utc_offset: 7200000,
      waitlist_count: 53,
      yes_rsvp_count: 200,
      venue: {
        id: 26112492,
        name: 'Google',
        lat: 48.143035888671875,
        lon: 11.541084289550781,
        repinned: true,
        address_1: 'Erika-Mann-Straße 33',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1381869297000,
        name: 'MUC++',
        id: 10704512,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'MUCplusplus',
        who: 'C++ aficionados',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/MUCplusplus/events/260314997/',
      description: '<p>Exception Handling is probably one of the most controversial features in C++, with many code bases outright banning them from the start, or only allowing their use in very specific cases. The reasons for this are often unclear and founded on premises that are not well understood.</p> <p>In this talk, we will explain exception handling from the bottom up, taking a close look at what a compiler actually has to do to implement the mechanism. Instead of focusing on a specific implementation, we will approach the problem from a more abstract, language-design point of view, allowing us to explore the different approaches an implementation could choose. In the end, we will gain a deeper understanding for the problems associated with the feature and how they could be mitigated in the future by alternative language features like the proposed static exceptions.</p> <p>Agenda:<br/>18:30 -- Entry<br/>19:00 -- Welcome at Google with Food and Drinks<br/>19:30 -- 1. Lightning Talk<br/>~19:45 -- 2. Lightning Talk<br/>~20:00 -- Exceptions Demystified (Andreas Weis)<br/>~21:15 -- Open Discussions<br/>22:00 -- Official End</p> ',
      visibility: 'public'
    },
    {
      created: 1554987750000,
      duration: 19800000,
      id: '260535959',
      name: 'Google I/O Extended Munich 2019',
      rsvp_limit: 100,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1557243000000,
      local_date: '2019-05-07',
      local_time: '17:30',
      updated: 1555494305000,
      utc_offset: 7200000,
      waitlist_count: 88,
      yes_rsvp_count: 102,
      venue: {
        id: 26112492,
        name: 'Google',
        lat: 48.143035888671875,
        lon: 11.541084289550781,
        repinned: true,
        address_1: 'Erika-Mann-Straße 33',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1448316136000,
        name: 'GDG Munich Android',
        id: 19149051,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'GDG-Munich-Android',
        who: 'Humble Android Coders',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/GDG-Munich-Android/events/260535959/',
      description: '<p>Google I/O 2019! Let\'s enjoy the live stream of the event together in Munich.</p> <p>You were too late to get a spot? There\'s a **second** location at 1und1 - check this event: <a href="https://www.meetup.com/GDG-Munich-Android/events/260639431/" class="linkified">https://www.meetup.com/GDG-Munich-Android/events/260639431/</a></p> <p>Preliminary Agenda:<br/>17:30 Arrival, networking, food &amp; drinks<br/>19:00 Key Note<br/>20:45 Lightning talks (5-7 minutes, contact us if you want to present!)<br/>21:45 Developer Key Note<br/>22:45 End</p> <p>NOTE: If you are attending, we need your first and last name. If your meetup profile does not show your real name, please change that or reach out to us and tell us. This is required for attending the meeting.</p> <p>Lightning talks: Please reach out to us if you would like to present. Tell us about your topic (send slides if you have already them or just a very short outline otherwise) and how long your talk will be. Your topic should also consider that we are expecting a mixed group including "non-Android" people.</p> ',
      visibility: 'public',
      pro_is_email_shared: false
    },
    {
      created: 1555409541000,
      duration: 7200000,
      id: '260666142',
      name: 'Fuckup Nights Munich - Vol. II 2019',
      rsvp_limit: 150,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1561568400000,
      local_date: '2019-06-26',
      local_time: '19:00',
      rsvp_close_offset: 'PT168H',
      updated: 1556110482000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 47,
      venue: {
        id: 26328091,
        name: 'IHK Academy Munich',
        lat: 48.124412536621094,
        lon: 11.59816837310791,
        repinned: true,
        address_1: 'Orleansstraße 10-12',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1443688096000,
        name: 'TechDivision TechTalk München',
        id: 18985124,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'TechDivision-TechTalk-Munchen',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/TechDivision-TechTalk-Munchen/events/260666142/',
      description: '<p>Bei diesem Event handelt es sich um eine inzwischen weltweite Bewegung, die mittlerweile in mehr als 300 Städten in über 80 Ländern weltweit stattfindet! Jetzt gibt es dieses Event auch offiziell in München!</p> <p>"Fuckup Nights" klingt anrüchig? Ist es aber nicht! An diesem Abend haben vier Personen das Wort, die zur Abwechslung mal nicht von großen Erfolgsgeschichten erzählen, sondern mit Witz, Humor und aller Offenheit davon berichten, wie es auch mal schief laufen kann - damit sind wir bei den sog. Fuck Ups.</p> <p>Schaut Euch einfach das Video dazu an: <a href="https://www.youtube.com/embed/xtH6zGSeuDI" class="embedded">https://www.youtube.com/embed/xtH6zGSeuDI</a></p> <p>Ein paar Impressionen von der ersten Fuckup Night Munich in diesem Jahr bei HIRMER mit 270 Teilnehmern bekommt ihr unter nachfolgendem Link: <a href="https://www.youtube.com/watch?v=nBUtn5o9-Tc" class="embedded">https://www.youtube.com/watch?v=nBUtn5o9-Tc</a></p> <p>Fehler passieren eben und das im privaten Umfeld wie auch im Job - vom Ein-Mann Betrieb bis hin zu globalen Konzernen, nur wird darüber häufig nicht oder kaum gesprochen. Genau das wollen wir ändern! Im Rahmen der Fuckup Nights, soll genau darüber ganz offen gesprochen und diskutiert werden!</p> <p>ABER WARUM DAS GANZE?<br/>Ganz einfach! Weil man bekanntlich aus Fehlern lernt! Etwas erst gar nicht zu versuchen ist am Ende viel schlechter, wie etwas auszuprobieren und dann zu scheitern. Also nur wenn man etwas wagt und ausprobiert, kann man erst sicher sein, ob es überhaupt funktioniert. Wir sind daher überzeugt davon, dass man aus den meisten Misserfolgen etwas gewinnen und mitnehmen kann. Daher werden wir sicherlich auch einen unserer unzähligen FuckUps präsentieren. Ganz offen und ohne Filter!</p> <p>Die „Fuckup-Nights“ sind also dazu da, öffentlich über schief gelaufenen Projekte, Arbeiten und Ideen zu sprechen und diese Erfahrung mit der Community zu teilen. In lockerer Atmosphäre werden an diesem Abend wertvolle Erfahrungen von erfolgreichen Managern, Unternehmen und Startups weitergegeben, um daraus zu lernen. Natürlich gibt´s auch Snacks und Getränke, damit das Ganze nicht zu trocken wird!</p> <p>Es warten einige Überraschungen... ;-)</p> <p>WICHTIG: Die Teilnahme ist ausschließlich nach vorheriger Anmeldung über nachfolgenden Link möglich: <a href="https://fuckupnights.com/munich/" class="linkified">https://fuckupnights.com/munich/</a><br/>First come - first serve!</p> ',
      visibility: 'public'
    },
    {
      created: 1554479262000,
      duration: 10800000,
      id: '260373931',
      name: 'AWS UG May Event',
      rsvp_limit: 120,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1557937800000,
      local_date: '2019-05-15',
      local_time: '18:30',
      updated: 1554482034000,
      utc_offset: 7200000,
      waitlist_count: 4,
      yes_rsvp_count: 120,
      venue: {
        id: 26303862,
        name: 'NTT DATA Deutschland GmbH',
        lat: 48.18416976928711,
        lon: 11.587780952453613,
        repinned: true,
        address_1: 'Hans-Döllgast-Straße 26',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1400514197000,
        name: 'Munich AWS User Group',
        id: 14546712,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'AWS-Munich',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/AWS-Munich/events/260373931/',
      description: '<p>It\'s May and the summer is coming to the most beautiful city in the world!<br/>But this doesn\'t stop us from visiting the fifth sponsor this year!<br/>We\'re very thankful that NTT Data (<a href="https://de.nttdata.com/" class="linkified">https://de.nttdata.com/</a>) is providing food, drinks and their offices for our meetup!</p> <p>AGENDA:<br/>18:30 - Doors open, networking, drinks, food<br/>19:00 - Markus (Team Internet AG) - Recent AWS announcements<br/>19:45 - Krasimir Dzhigovechki &amp; Wolfgang Unger (NTT Data) - Container Orchestration in AWS: ECS vs. EKS<br/>On AWS you can run containers either with ECS or the new AWS service EKS.<br/>While ECS is quite established and well supported on AWS, EKS was launched much later, to finally support Kubernetes on AWS.<br/>We want to show up the differences between ECS and EKS, talk about advantages and disadvantages of both solutions and point<br/>Out to you, in which situation or use case you should choose the one or the other.<br/>We will present live demos on both services and then make a comparison of both container services.<br/>20:45 - More drinks, more networking</p> <p>If you have an office or coworking space where we can meet [masked] people), want to sponsor drinks/food or have a (lightning) talk you want to present - please let us know!</p> ',
      visibility: 'public'
    },
    {
      created: 1555342805000,
      duration: 7200000,
      id: '260643142',
      name: 'PyData April: Talks on Kotlin & Computer Vision',
      rsvp_limit: 100,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1556557200000,
      local_date: '2019-04-29',
      local_time: '19:00',
      updated: 1555512566000,
      utc_offset: 7200000,
      waitlist_count: 12,
      yes_rsvp_count: 100,
      venue: {
        id: 26090924,
        name: 'JetBrains Event Space',
        lat: 48.13762664794922,
        lon: 11.5233154296875,
        repinned: true,
        address_1: 'Elsenheimerstraße 47A',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1469524975000,
        name: 'PyData Munich',
        id: 20225730,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'PyData-Munchen',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/PyData-Munchen/events/260643142/',
      description: '<p>PyData Munich is back with a couple of accessible data science tutorials!</p> <p>Schedule:<br/>- 18:30 Doors open<br/>- 19:00 Welcome to PyData Munich<br/>- 19:10 “Kotlin 💕 Data Science?” by Preslav Rachev, Senior Backend Engineer @ KI labs</p> <p>Software engineering and data science are two very different disciplines. Accommodating both in the same project is not trivial. The key to success relies on developers and data scientists having a middle ground where they could do their work productively, and without affecting the other side. Preslav\'s talk will try to revisit Kotlin as a language potentially suiting both sides. He will reflect on its advantages, and also the current roadblocks.</p> <p>Preslav is a Java/Python double agent with over 10 years of cumulative programming experience (both in industry and academia). He loves open-source software, making music, writing, and distance running.</p> <p>- 19:55 “Introduction to Computer Vision” by Anton Kasyanov, Senior Machine Learning Engineer @ DataRobot</p> <p>The talk is aimed at the engineers who are curious about the area and have no prior experience with it. The main goal is to give the feel of what is it all about, what problems can be solved and some basic methods to do that.</p> <p>Anton works as a Senior Machine Learning Engineer in DataRobot for almost two years. Prior to that, he did a lot of backend and ML development using Python. He got his Computer Science Masters degree in RWTH Aachen (Germany) with a focus on Computer Vision.</p> <p>- 20:40 Job advertisements and networking with beer and pizza</p> <p>Many thanks to JetBrains (<a href="https://www.jetbrains.com/" class="linkified">https://www.jetbrains.com/</a>) for hosting and sponsoring this event!</p> <p>Hope to see you there!<br/>Connor &amp; Nithish</p> <p>P.S.: If you are interested in giving a talk or hosting an event, please contact one of the organizers!<br/>If you are looking for inspiration for a talk topic or want to request one, please check out the ever-growing lists of topics here: <a href="https://docs.google.com/document/d/1wrdv27B7UGRJelbk8EQdHmBZ8uuO0I4q2JlJrsiCGlI/edit?usp=sharing" class="linkified">https://docs.google.com/document/d/1wrdv27B7UGRJelbk8EQdHmBZ8uuO0I4q2JlJrsiCGlI/edit?usp=sharing</a></p> ',
      visibility: 'public',
      pro_is_email_shared: false
    },
    {
      created: 1371224928000,
      id: 'drpzdgyzhblb',
      name: 'Ruby User Group Meetup',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1557334800000,
      local_date: '2019-05-08',
      local_time: '19:00',
      updated: 1507810525000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 4,
      group: {
        created: 1370808069000,
        name: 'Munich Rubyshift, Ruby User Group',
        id: 8851722,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munich-Rubyshift-Ruby-User-Group',
        who: 'Rubyists',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Munich-Rubyshift-Ruby-User-Group/events/drpzdgyzhblb/',
      description: '<p>We\'re actively searching for speakers! Want to become one? Ping us!</p> ',
      visibility: 'public'
    },
    {
      created: 1554185779000,
      duration: 10800000,
      id: '260271104',
      name: 'Flutter talks in June',
      rsvp_limit: 120,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1559836800000,
      local_date: '2019-06-06',
      local_time: '18:00',
      updated: 1555153661000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 35,
      group: {
        created: 1543101111000,
        name: 'Flutter Munich',
        id: 30587470,
        join_mode: 'approval',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Flutter-Munich',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Flutter-Munich/events/260271104/',
      description: '<p>PRESENTATIONS:</p> <p>🎤 Krzysztof Sroka 🎤<br/>60 FPS or bust 📈<br/>⏱30 min</p> <p>Flutter lets you write incredibly smooth animations with its promise of 60 FPS refresh rate. But to achieve that you need to make sure that you don\'t slow yourself down. In the talk I\'ll describe how Flutter renders widgets, what does it mean for you, present some common pitfalls you should avoid, and finally show what you can do using the provided debugging tools.</p> <p>CONTRIBUTE:</p> <p>🗣️ If you would like to share your experience with Flutter, please feel free to contact me at any time. We have slots for presentations at this event and we are already organizing the next events.</p> <p>🍕 Would you or your company like to host one of our upcoming events? Send me a message!</p> ',
      visibility: 'public'
    },
    {
      created: 1552730271000,
      duration: 10800000,
      id: '259817783',
      name: '2. Agiles Projektmanagement Trendforum am 27.Juni 2019 (WERK1 München)',
      rsvp_limit: 80,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1561654800000,
      local_date: '2019-06-27',
      local_time: '19:00',
      updated: 1553721073000,
      utc_offset: 7200000,
      waitlist_count: 27,
      yes_rsvp_count: 80,
      venue: {
        id: 26052503,
        name: 'WERK1 München',
        lat: 48.123779296875,
        lon: 11.608209609985352,
        repinned: true,
        address_1: 'Atelierstraße 29',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1430647334000,
        name: 'Projektmanagement Meetup Roundtable',
        id: 18574027,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Projektmanagement-Meetup-Roundtable',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Projektmanagement-Meetup-Roundtable/events/259817783/',
      description: '<p>2. Agiles Projektmanagement Trendforum / Meetup am Donnerstag, den 27. Juni 2019 bei WERK1, München</p> <p>Referenten:<br/>Herr Andreas Hock:<br/>Partner, 3Pworx GmbH, seit ca. 20 Jahren zertifizierter Trainer und Berater für klassisches, agiles und hybrides Projekt- und Portfoliomanagement, PM-Publizist und Buchautor, Erfolgscoach, Motivator und Wissensmanager.</p> <p>Herr Steffen Jakob:<br/>Steffen Jakob ist Diplom-Wirtschaftsingenieur und leitet seit 2013 den Geschäftsbereich Projekt- und Requirements-Management der Haufe Gruppe. In dieser Funktion verantwortet er das Haufe-Projektportfolio.<br/>Er begann seine Karriere bei einem großen internationalen Medienunternehmen und arbeitete anschließend in unterschiedlichen Führungsfunktionen bei IT-Beratungsunternehmen.</p> <p>Herr Timo Bass:<br/>Timo Bass leitet den Bereich Strategische Projektportfolio Steuerung @ CreditPlus (Credit Agricole). Er ist PMP nach PMI, SAFe Program Consultant (SPC), Design Thinking Coach und war früher u.a. für das Beratungshaus Accenture Strategy erfolgreich tätig.</p> <p>Agenda:<br/>18:00 Uhr - Empfang, Get-Together I mit Drinks und Snacks sowie erstes Kennenlernen</p> <p>19:00 Uhr - Begrüßung und Einführung durch 3Pworx GmbH, WERK1</p> <p>19:15 Uhr – Vortrag 1: -&gt; „Vom Religionskrieg zur Ökumene“ – klassische und agile Vorgehensweisen bei der Haufe-Group</p> <p>Vortrag Haufe-Group von Herrn Steffen Jakob</p> <p>20:00 Uhr – Vortrag 2: Eine gemeinsame Reise zu einer Lean &amp; Agile Organisation – Mehr eine Revolution als Transformation!</p> <p>Vortrag von Credit Plus Bank, Herr Timo Bass (Leiter Strategische Portfoliosteuerung)</p> <p>21:00 Uhr – Vortrag 3: Agile Methoden im Vergleich – Scrum vs. KANBAN vs. SAFe, usw.</p> <p>Wie finde ich die „richtige“ agile Methodik, welche idealerweise zu meinem Unternehmen und agilen Projekten passt.</p> <p>Vortrag von Herrn Andreas Hock, Partner 3Pworx GmbH</p> <p>21:30 Uhr - Gemütliches Ausklingen in der Werk1 Lounge mit Snacks &amp; Drinks</p> <p>ca. 22:00 Uhr - Ende des 3Pworx 2. Agilen Trendforums Juni 2019</p> <p>Selbstverständlich ist diese Veranstaltung für Sie kostenfrei.</p> <p>Genaue Veranstaltungsdetails:<br/>Termin: Donnerstag, den 27. Juni 2019; Zeit 18:00 – ca. 22:00 Uhr<br/>Ort: WERK1</p> <p>Anmeldung:<br/>Bitte senden Sie uns Ihre Teilnehmerdaten über das Anmeldeformular auf www.3pworx.com oder senden Sie eine kurze Email an [masked] . Eine Anmeldung ist auch über das XING – Event oder die Meetup-Gruppe möglich.</p> <p>Gerne können Sie die Einladung, wenn Sie möchten, auch an Kolleginnen oder Kollegen sowie Interessierte des PM Meetups 2019 weiterleiten oder weiterempfehlen.<br/>Mit freundlichen Grüßen<br/>Ihr 3Pworx-Team</p> ',
      how_to_find_us: 'https://www.werk1.com',
      visibility: 'public'
    },
    {
      created: 1548946504000,
      duration: 27000000,
      id: '258560164',
      name: 'Global DevOps Bootcamp 2019',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1560582000000,
      local_date: '2019-06-15',
      local_time: '09:00',
      rsvp_open_offset: 'PT1190H',
      updated: 1550157995000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 8,
      group: {
        created: 1397242023000,
        name: 'Agile Munich',
        id: 13860382,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'AgileMunich',
        who: 'Agile Practitioners',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/AgileMunich/events/258560164/',
      description: '<p>As with previous two years, we\'re bringing you this year\'s Global DevOps Bootcamp on June 15th. Stay tuned and mark your calendars...</p> <p>Get in touch if you wish to sponsor.</p> <p>More details to follow shortly.</p> ',
      visibility: 'public'
    },
    {
      created: 1554382076000,
      duration: 7200000,
      id: '260339373',
      name: 'Design Thinking bei On Demand Mikroversicherungen mittels Blockchain Technologie',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1556208000000,
      local_date: '2019-04-25',
      local_time: '18:00',
      updated: 1554382076000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 30,
      venue: {
        id: 26170224,
        name: 'Zielpuls GmbH München',
        lat: 48.18381118774414,
        lon: 11.586676597595215,
        repinned: false,
        address_1: 'Domagkstraße 14',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1521464337000,
        name: 'TechTalk at Zielpuls',
        id: 27876639,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'TechTalk-Zielpuls',
        who: 'Mitglieder',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/TechTalk-Zielpuls/events/260339373/',
      description: '<p>Unser TechTalk@Zielpuls im April wird von unseren Beratern Alexander Lipski und Dr. Timm Bergholz gestaltet. Sie bringen uns ihre Erfahrungen aus der Entwicklung eines Blockchain Use Cases mit.</p> <p>Unser Vortrag wird folgende Schwerpunkte behandeln:<br/>• Konzeptionierung des Use Cases und Ableitung von IT-Architekturen sowie möglicher Blockchain Plattformen<br/>• Erstellen eines Prototypen mittels Solidity in der ETH-Blockchain</p> ',
      how_to_find_us: 'Check-in im 1. OG',
      visibility: 'public'
    },
    {
      created: 1555421464000,
      duration: 7200000,
      id: '260668963',
      name: 'Building Smarter IoT Products with Edge AI - Talks by Intel, Microsoft and TI',
      rsvp_limit: 200,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1559146500000,
      local_date: '2019-05-29',
      local_time: '18:15',
      updated: 1555494078000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 26,
      group: {
        created: 1490683239000,
        name: 'Munichs robotics meetup',
        id: 23035493,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munichs-robotics-meetup',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Munichs-robotics-meetup/events/260668963/',
      description: '<p>In order to participate, you must download your FREE TICKET here (<a href="https://cli.re/LoWByr" class="linkified">https://cli.re/LoWByr</a>). If you only register on Meetup.com you won’t be eligible to attend the event and won’t be able to know the venue. Thank you!</p> <p>This event is organised in collaboration with Hardware Pioneers (<a href="https://hardwarepioneers.com" class="linkified">https://hardwarepioneers.com</a>).</p> <p>AI is moving towards edge devices, making connected things become even more intelligent. Curious about discovering how Edge AI can bring huge benefits to your IoT design? Then join us<br/>on the 29th of May to learn more from:<br/>- One of the top ten semiconductor companies worldwide (Texas Instruments).<br/>- The world\'s largest semiconductor chip maker (Intel).<br/>- One of the biggest multinational technology companies and the creator of the Azure IoT platform<br/>(Microsoft).</p> <p>Drinks and pizza will be served throughout the night.</p> ',
      visibility: 'public'
    },
    {
      created: 1554903176000,
      duration: 21540000,
      id: '260505169',
      name: 'BSH Future Home Demo Day - powered by Techstars',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1557417600000,
      local_date: '2019-05-09',
      local_time: '18:00',
      updated: 1554903187000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 37,
      venue: {
        id: 26286188,
        name: 'Mathäser Filmpalast',
        lat: 48.13914489746094,
        lon: 11.563968658447266,
        repinned: false,
        address_1: 'Bayerstraße 3-5',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1491205628000,
        name: 'Munich Tech',
        id: 23120315,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Munich-Tech',
        who: 'Members',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/Munich-Tech/events/260505169/',
      description: '<p>*** REGISTRATION ON EVENTBRITE MANDATORY ***</p> <p>&gt;&gt;&gt; <a href="https://techstarsbshdemoday2019.eventbrite.com" class="linkified">https://techstarsbshdemoday2019.eventbrite.com</a> &lt;&lt;&lt;</p> <p>Are you interested in hearing about the latest developments in Future Home and Connected Kitchen innovations?</p> <p>Join us for the BSH Future Home Accelerator Powered by Techstars Demo Day as our founders share the innovative companies and the products and services they are building.</p> <p>Agenda:</p> <p>18:00 Doors Open &amp; Registration<br/>19:00 Welcoming remarks &amp; company presentations<br/>21:00 - 23:59 Networking &amp; Afterparty</p> ',
      visibility: 'public'
    },
    {
      created: 1554664387000,
      duration: 7200000,
      id: '260427919',
      name: 'DevOps is neither the Answer nor the Question!',
      rsvp_limit: 75,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1559754000000,
      local_date: '2019-06-05',
      local_time: '19:00',
      updated: 1555436986000,
      utc_offset: 7200000,
      waitlist_count: 19,
      yes_rsvp_count: 88,
      venue: {
        id: 26056635,
        name: 'MaibornWolff GmbH',
        lat: 48.133201599121094,
        lon: 11.54609203338623,
        repinned: true,
        address_1: 'Theresienhöhe 13',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1391009463000,
        name: 'DevOps Munich',
        id: 12572892,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'DevOpsMunich',
        who: 'DevOps',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/DevOpsMunich/events/260427919/',
      description: '<p>DevOps: Ist das Kunst oder kann das weg? Eine knappe Dekade ist das Buzzword alt. In dieser Zeit ist das unscharfe Buzzword zu einem handfesten Thema geworden, das in etlichen Unternehmen sehr ernsthaft diskutiert wird und viel Sinn stiftet. Denn DevOps ist viel mehr als eine Gruppentherapie für frustrierte ITler mit neuen fancy Tools! Es betrifft mindestens den kompletten Arbeitsalltag. Ein Kultur-Refactoring, das es in sich hat und in besonders großen Projekten besonders große technische und organisatorische Herausforderungen mit sich bringt.</p> <p>An welchen Stellen bei der Einführung von DevOps-Methoden kann es zu Problemen kommen? Was sind die technischen Symptome? Bei welchen Problemen liegt die Ursache dagegen gar nicht in der Technik? Wie kann man sich der Problemlösung annähern? Dieser Vortrag bietet keine DevOps-Einführung, sondern geht dorthin, wo es beim Einsatz in großen Projekten, lange nach der vermeintlichen Einführung, weh tut. Wir identifizieren potentielle Ursachen und diskutieren mögliche Auswege.</p> <p>## Links</p> <p><a href="https://talks.arbe.io" class="linkified">https://talks.arbe.io</a> (Slides)<br/><a href="https://feedback.arbe.io" class="linkified">https://feedback.arbe.io</a> (Feedback)<br/><a href="https://twitter.com/arnisoph" class="linkified">https://twitter.com/arnisoph</a> (Twitter)</p> <p>## Vorkenntnisse</p> <p>Existierende praktische Erfahrung in der (agilen) Entwicklung und im Betrieb von skalierenden bzw. hochverfügbaren Anwendungen helfen beim Verständnis der vorgetragenen Herausforderungen.</p> <p>## Lernziele</p> <p>Behandelt werden untechnische weiche Faktoren, die zu Misserfolgen im Tagesgeschäft führen, trotz und vielleicht wegen des Einsatzes von DevOps-Methoden.</p> <p>## Speaker Bio</p> <p>Arnold uses great technologies to move companies in Germany beyond #Neuland. As Senior Systems Engineer at inovex he\'s working on software-defined datacenter management, continuous integration/delivery, getting rid of the *legacy stuff* and is especially interested in system &amp; software architecture. At the end of the day he loves to get outside with his MTB.</p> ',
      how_to_find_us: 'The room for our meetup is on the 5th floor. 🏢',
      visibility: 'public'
    },
    {
      local_time: '19:00',
      local_date: '2019-05-21',
      link: 'https://www.meetup.com/Software-Performance-Meetup-Group/events/259928984/',
      visibility: 'public_limited',
      group: {
        created: 1400662449000,
        name: 'Software Performance Meetup Group',
        id: 14586172,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'Software-Performance-Meetup-Group',
        who: 'Performance Management Worker',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      waitlist_count: 0,
      yes_rsvp_count: 45,
      duration: 7200000,
      time: 1558458000000,
      utc_offset: 7200000,
      name: '19th Software Performance Meetup',
      id: '259928984'
    },
    {
      created: 1555333391000,
      duration: 19800000,
      id: '260639431',
      name: 'Google I/O Extended Munich 2019, 2nd Location at 1&1',
      rsvp_limit: 90,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1557243000000,
      local_date: '2019-05-07',
      local_time: '17:30',
      updated: 1555485985000,
      utc_offset: 7200000,
      waitlist_count: 0,
      yes_rsvp_count: 35,
      venue: {
        id: 26051667,
        name: '1&1 Company',
        lat: 48.16843032836914,
        lon: 11.537059783935547,
        repinned: true,
        address_1: 'Sapporobogen 6-8',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1448316136000,
        name: 'GDG Munich Android',
        id: 19149051,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'GDG-Munich-Android',
        who: 'Humble Android Coders',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/GDG-Munich-Android/events/260639431/',
      description: '<p>***** Please note, there are two GDG Munich I/O events: *****<br/>***** Check which location you are RSVP\'d for *****</p> <p>Google I/O 2019! Let\'s enjoy the live stream of the event together at 1&amp;1 in Munich.</p> <p>Your host and contact at 1&amp;1 is Christoph Klar ([masked]).</p> <p>Preliminary Agenda:<br/>17:30 Arrival, networking, food &amp; drinks<br/>19:00 Key Note<br/>20:45 TBD / Lightning talks (5-7 minutes, contact us if you want to present!)<br/>21:45 Developer Key Note<br/>22:45 End</p> <p>NOTE: If you are attending, we need your first and last name. If your meetup profile does not show your real name, please change that or reach out to us and tell us. This is required for attending the meeting.</p> <p>Lightning talks: Please reach out to us if you would like to present. Tell us about your topic (send slides if you have already them or just a very short outline otherwise) and how long your talk will be. Your topic should also consider that we are expecting a mixed group including "non-Android" people.</p> <p>***** Please note, there are two GDG Munich I/O events: *****<br/>***** Check which location you are RSVP\'d for *****</p> ',
      visibility: 'public',
      pro_is_email_shared: false
    },
    {
      created: 1555007688000,
      duration: 7200000,
      id: '260545051',
      name: 'DevOps Meetup May 2019',
      rsvp_limit: 70,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1557162000000,
      local_date: '2019-05-06',
      local_time: '19:00',
      updated: 1555147720000,
      utc_offset: 7200000,
      waitlist_count: 42,
      yes_rsvp_count: 70,
      venue: {
        id: 26082467,
        name: 'codecentric AG',
        lat: 48.13685989379883,
        lon: 11.523862838745117,
        repinned: true,
        address_1: 'Elsenheimerstraße 55A',
        city: 'München',
        country: 'de',
        localized_country_name: 'Germany'
      },
      group: {
        created: 1391009463000,
        name: 'DevOps Munich',
        id: 12572892,
        join_mode: 'open',
        lat: 48.13999938964844,
        lon: 11.579999923706055,
        urlname: 'DevOpsMunich',
        who: 'DevOps',
        localized_location: 'München, Germany',
        state: '',
        country: 'de',
        region: 'en_US',
        timezone: 'Europe/Berlin'
      },
      link: 'https://www.meetup.com/DevOpsMunich/events/260545051/',
      description: '<p># Continuous Delivery like you know no fear</p> <p>Warning: This talk can make your own release process seem awfully slow and risky! Everybody does Continuous Integration - more or less, but I think a modern CD pipeline can fundamentally change the way we are collaborating while building Software. At Matmatch we\'re pushing the boundaries of what Continuous Delivery can be by leveraging Gitlab and Kubernetes: Every Branch gets deployed into its own environment - and the Product Manager or the Stakeholder can release every feature directly to production with the click of a button. We don\'t bundle releases anymore, every feature goes straight to production. Goodbye test systems, good riddance staging processes.</p> <p>Why did we, as a small startup, bother with pushing that system to its limits? To get faster feedback and to minimize risk! By releasing and failing faster than the rest, we are outpacing others when it comes to opportunities to learn. It\'s a joy to work that way and and we could never imagine going back.</p> <p>In this talk I will walk you through our pipeline, the hiccups we had along the way to build it and the benefits we get from having this pipeline in place.</p> <p>## Speaker Bio</p> <p>Chris was a senior software consultant for a few years before he joined Matmatch as Head of Engineering, where he saw a huge variety of distributed systems and made a huge variety of mistakes that he can share now. He is especially interested in distributed systems, microservice architectures and always curious about how all these pieces fit together</p> ',
      visibility: 'public'
    }
  ]
};
export { mockEvents };

// const mockEvents = {
//   city: {
//     id: 1007700,
//     city: 'München',
//     lat: 48.14,
//     lon: 11.58,
//     state: '',
//     country: 'de',
//     zip: 'meetup3',
//     member_count: 1257,
//   },
//   events: [
//     {
//       created: 1557483479000,
//       duration: 46800000,
//       id: '261346344',
//       name: 'Easy Hike : Breitachklamm [13.8km, 350m gain]',
//       rsvp_limit: 20,
//       date_in_series_pattern: false,
//       status: 'upcoming',
//       time: 1561005900000,
//       local_date: '2019-06-20',
//       local_time: '06:45',
//       rsvp_close_offset: 'PT18H45M',
//       updated: 1558600416000,
//       utc_offset: 7200000,
//       waitlist_count: 60,
//       yes_rsvp_count: 20,
//       venue: {
//         id: 26183168,
//         name: 'Munich Hauptbahnhof (Main Station)',
//         lat: 48.14141845703125,
//         lon: 11.557615280151367,
//         repinned: true,
//         address_1: 'Arnulfstraße 15',
//         city: 'München',
//         country: 'de',
//         localized_country_name: 'Germany',
//       },
//       group: {
//         created: 1389721197000,
//         name: 'Hiking near Munich',
//         id: 12113182,
//         join_mode: 'open',
//         lat: 48.13999938964844,
//         lon: 11.579999923706055,
//         urlname: 'Hiking-near-Munich',
//         who: 'Munich hikers',
//         localized_location: 'München, Germany',
//         state: '',
//         country: 'de',
//         region: 'en_US',
//         timezone: 'Europe/Berlin',
//       },
//       link: 'https://www.meetup.com/Hiking-near-Munich/events/261346344/',
//       description: '<p>Hey y´all</p> <p>Another easy and relaxed one.</p> <p>Hoping the weather will be okay - I would love to go with you! </p> ',
//       how_to_find_us: 'Shop at Platforms 27-36',
//       visibility: 'public',
//     },
//     {
//       local_time: '19:00',
//       local_date: '2019-06-13',
//       link: 'https://www.meetup.com/rice-cookie-improv/events/flrdzqyzjbrb/',
//       visibility: 'public_limited',
//       group: {
//         created: 1468649601000,
//         name: 'Rice Cookie Improvtheater in Munich',
//         id: 20189476,
//         join_mode: 'open',
//         lat: 48.13999938964844,
//         lon: 11.579999923706055,
//         urlname: 'rice-cookie-improv',
//         who: 'Improv-Enthusiasts',
//         localized_location: 'München, Germany',
//         state: '',
//         country: 'de',
//         region: 'en_US',
//         timezone: 'Europe/Berlin',
//       },
//       waitlist_count: 3,
//       yes_rsvp_count: 10,
//       duration: 7200000,
//       time: 1560445200000,
//       utc_offset: 7200000,
//       name: 'Workshop: Get loose with Improv Theater',
//       id: 'flrdzqyzjbrb',
//     },
//     {
//       created: 1558336922000,
//       duration: 39600000,
//       id: '261608978',
//       name: 'Longer Hike: Starnberg - Maisinger See - Herrsching [19km; 230m gain]',
//       rsvp_limit: 25,
//       date_in_series_pattern: false,
//       status: 'upcoming',
//       time: 1562996700000,
//       local_date: '2019-07-13',
//       local_time: '07:45',
//       rsvp_close_offset: 'PT19H45M',
//       updated: 1558508997000,
//       utc_offset: 7200000,
//       waitlist_count: 53,
//       yes_rsvp_count: 25,
//       venue: {
//         id: 26183168,
//         name: 'Munich Hauptbahnhof (Main Station)',
//         lat: 48.14128875732422,
//         lon: 11.559012413024902,
//         repinned: true,
//         address_1: 'Arnulfstraße 15',
//         city: 'München',
//         country: 'de',
//         localized_country_name: 'Germany',
//         },
//         group: {
//           created: 1389721197000,
//           name: 'Hiking near Munich',
//           id: 12113182,
//           join_mode: 'open',
//           lat: 48.13999938964844,
//           lon: 11.579999923706055,
//           urlname: 'Hiking-near-Munich',
//           who: 'Munich hikers',
//           localized_location: 'München, Germany',
//           state: '',
//           country: 'de',
//           region: 'en_US',
//           timezone: 'Europe/Berlin',
//         },
//         link: 'https://www.meetup.com/Hiking-near-Munich/events/261608978/',
//         description: '<p>Hey y´all</p> <p>For everyone who is not joining on 30th May or wanting something a little longer: Here we go :)</p> <p>Hoping the weather will be okay - I would love to go to one of my most loved places with you!</p> <p>We would meet at 07:45am at the Central Station; in front of the lower Starbucks (North Entrance of Main Hall, take staircase to mid-level just before you head to S-Bahn level)</p> <p>The tour itself is at 19km, 270m gain. It should take around 6-7 hours, depending on how relaxed we take it and how long we stay at the Biergarten for lunch. You can either take something to eat with you and buy something. We might also be able to have an early dinner at Kloster Andechs.</p> <p>Tipp:<br/>Take swimming gear with you, if you feel like taking a dive into the water :)</p> <p>Train Journey Details:<br/>Departure 08.32 Uhr / S6 to Starnberg, Exit at Starnberg<br/>Return / S8 from Herrsching</p> <p>Ticket Information:<br/>Please make sure to have proper MVG Tickets. We will have the opportunity to buy group-day-tickets when meeting; depending on the number of people joining.</p> <p>What is important:</p> <p>- Trekking Shoes to be recommended<br/>- enough water and snacks for along the way<br/>- swimming gear :)</p> <p>Kindly note that end of RSVP is on Friday, 12th July at 12pm. Anyone changing the status afterwards to no without a short email to me or anyone just not showing up will be marked as no show as a reference for future smaller hikes.</p> ',
//         visibility: 'public',
//     },
//     {
//       created: 1548414814000,
//       duration: 957600000,
//       id: '258384273',
//       name: 'Lechtalweg - Lech Route',
//       rsvp_limit: 22,
//       date_in_series_pattern: false,
//       status: 'upcoming',
//       time: 1566979200000,
//       local_date: '2019-08-28',
//       local_time: '10:00',
//       updated: 1559492619000,
//       utc_offset: 7200000,
//       waitlist_count: 1,
//       yes_rsvp_count: 22,
//       venue: {
//         id: 26044376,
//         name: 'Munich Central Station',
//         lat: 48.14026641845703,
//         lon: 11.55999755859375,
//         repinned: true,
//         address_1: 'Bayerstraße 10A',
//         city: 'München',
//         country: 'de',
//         localized_country_name: 'Germany',
//       },
//       group: {
//         created: 1389721197000,
//         name: 'Hiking near Munich',
//         id: 12113182,
//         join_mode: 'open',
//         lat: 48.13999938964844,
//         lon: 11.579999923706055,
//         urlname: 'Hiking-near-Munich',
//         who: 'Munich hikers',
//         localized_location: 'München, Germany',
//         state: '',
//         country: 'de',
//         region: 'en_US',
//         timezone: 'Europe/Berlin',
//       },
//       link: 'https://www.meetup.com/Hiking-near-Munich/events/258384273/',
//       description: '<p>[UPDATE]<br/>Let´s meet on Wednesday, 8th May at 06.30pm to talk routes, arrangements, etc. I would send out an email with the location prior to this day.</p> <p>[INFORMATION]<br/>I am currently in the process of booking my accomodation. For everyone who is fairly certain that he/she would like to join. Feel free to send me an email and I will let you know where to book.</p> <p>The Lechweg offers an extraordinary nature experience; it accompanies the Lech for almost 125km. From its spring near the Formarinsee in the Austrian Alps to the Lechfall in Füssen, Germany.</p> <p>This is one of my challenges for 2019 and I would love to have some company! Are you up for it? :)</p> <p>This MeetUp is functioning as framework as I really would love the idea of getting to know you beforehand and even plan together. The below route is just an idea and can be changed to whatever suits us best.</p> <p>I would suggest for a meetup in a coffee shop - maybe around March - to discuss details and routes and locations to stay overnight.</p> <p>I am actually already really excited. Although I am suffering an injured ankle at the moment :) :) :) Looking forward to meeting you all!</p> <p>Current Route:<br/>Day 1/Wednesday 28th August<br/>Journey to Innerbraz (to be reached by train from Munich via Bludenz)</p> <p>Day 2/Thursday, 29th August - Mountain Day<br/>Innerbraz to Freibürger Hütte (Formarinsee) - 13km - 1´2300m elevation with overnight stay - Very good fitness required. Mostly accessible paths. Sure-footedness required.</p> <p>Day 3/Friday, 30th August - Lech Day<br/>Freibürger Hütte to Lech - 14km - 650m elevation - easy hike<br/>Overnight Stay in Lech am Arlberg</p> <p>Day 4/Saturday, 31st August - Mountain Day<br/>Lech am Arlberg to Stuttgarter Hütte - 10km - 1´100m elevation, uphill - Sure-footedness, sturdy shoes and alpine experience required</p> <p>Day 5/Sunday, 1st September- Mountain Day<br/>Stuttgarter Hütte to Steeg - 14km - 1240m elevation, downhill - Good fitness required. Mostly accessible paths. Sure-footedness required</p> <p>Day 6/Monday, 2nd September - Lech Day<br/>Steeg via Holzgau to Elbigenalp - 15km - 200m elevation along the river</p> <p>Day 7/ Tuesday, 3rd September - Lech Day<br/>Elbigenalp to Vorderhornbach - 17km - 400m elevation along the river</p> <p>Day 8/ Wednesday, 4th September - Lech Day<br/>Vorderhornbach to Weißenbach - 14,5km - 100m elevation along the river</p> <p>Day 9/Thursday, 5th September - Lech Day<br/>Weißenbach to Pflach - 14km - 100m elevation partly along the river and via panorama trail</p> <p>Day 10/ Friday, 6th September - Lech Day<br/>Pflach to Füssen via Alpsee and View to Neuschwanstein - 13km - 400m elevation</p> <p>Day 11/ Saturday, 7th September<br/>Journey back home</p> <p>Obviously I am not a trained tour leader of any kind. So participation is on your own responsibility. Each of us will be responsible for their own bookings in regards to train tickets, overnight stays etc.</p> ',
//       visibility: 'public',
//     },
//     {
//       local_time: '15:00',
//       local_date: '2019-06-15',
//       link: 'https://www.meetup.com/rice-cookie-improv/events/jlrdzqyzjbtb/',
//       visibility: 'public_limited',
//       group: {
//         created: 1468649601000,
//         name: 'Rice Cookie Improvtheater in Munich',
//         id: 20189476,
//         join_mode: 'open',
//         lat: 48.13999938964844,
//         lon: 11.579999923706055,
//         urlname: 'rice-cookie-improv',
//         who: 'Improv-Enthusiasts',
//         localized_location: 'München, Germany',
//         state: '',
//         country: 'de',
//         region: 'en_US',
//         timezone: 'Europe/Berlin',
//       },
//       waitlist_count: 0,
//       yes_rsvp_count: 9,
//       duration: 10800000,
//       time: 1560603600000,
//       utc_offset: 7200000,
//       name: 'Workshop: Get loose with Improv Theater',
//       id: 'jlrdzqyzjbtb',
//     },
//     {
//       created: 1559922617000,
//       duration: 7200000,
//       id: '262127908',
//       name: 'Weekly Eye Contact',
//       rsvp_limit: 100,
//       date_in_series_pattern: false,
//       status: 'upcoming',
//       time: 1560531600000,
//       local_date: '2019-06-14',
//       local_time: '19:00',
//       updated: 1559922644000,
//       utc_offset: 7200000,
//       waitlist_count: 0,
//       yes_rsvp_count: 26,
//       venue: {
//         id: 25392191,
//         name: 'Cafe Luitpold ',
//         lat: 48.14292907714844,
//         lon: 11.575007438659668,
//         repinned: true,
//         address_1: 'Brienner Straße 11 ',
//         address_2: '80333 München ',
//         city: 'München ',
//         country: 'de',
//         localized_country_name: 'Germany',
//       },
//       group: {
//         created: 1455135194000,
//         name: 'Eye Contact Munich',
//         id: 19551209,
//         join_mode: 'open',
//         lat: 48.13999938964844,
//         lon: 11.579999923706055,
//         urlname: 'eye-contact-munich',
//         who: 'Members',
//         localized_location: 'München, Germany',
//         state: '',
//         country: 'de',
//         region: 'en_US',
//         timezone: 'Europe/Berlin',
//       },
//       link: 'https://www.meetup.com/eye-contact-munich/events/262127908/',
//       description: '<p>Hi All,</p> <p>bald ist es wieder soweit: ein großes Eye Contact Event!</p> <p>Eye-Contact bedeutet, Du setzt Dich gegenüber einer Person, die Du oft nicht mal kennst und blickst ihr einfach in die Augen, das ist alles. Einen Eindruck vom Experiment gewinnst du in diesem Video:<br/><a href=\'https://www.youtube.com/watch?v=1EumnijQBhw&amp;t=4s\' class=\'embedded\'>https://www.youtube.com/watch?v=1EumnijQBhw&amp;t=4s</a></p> <p>Bei diesen Events kommen Menschen jeglichen Alters, jeglicher Nation oder Glaubens zusammen und schauen sich einfach in die Augen. Aus Fremden werden Freund*innen, jede*r erlebt ganz unterschiedliche Dinge. Aber eines sagen die Teilnehmenden immer wieder: es ist wunderbar, zu erleben, wie einfach man sich mit Menschen verbinden kann!</p> <p>Neugierig geworden?</p> <p>Wir treffen uns am 14. Juni im Cafe Luitpold. Von 19.00 bis 21.00 Uhr werdet Ihr die Gelegenheit haben, Eure eigenen Erfahrungen zu machen.</p> <p>Wir freuen uns darauf Dich zu sehen. Bring auch gern Freund*innen mit.</p> <p>Eye Contact Munich</p> <p>Brienner Str. 11<br/>80333 München<br/>Eintritt: 4 EUR</p> ',
//       visibility: 'public',
//     },
//     {
//       created: 1558509204000,
//       duration: 7200000,
//       id: 'thdxzqyzjbvb',
//       name: 'Let\'s Play Kickball!',
//       rsvp_limit: 20,
//       date_in_series_pattern: false,
//       status: 'upcoming',
//       time: 1560682800000,
//       local_date: '2019-06-16',
//       local_time: '13:00',
//       rsvp_close_offset: 'PT2H',
//       updated: 1558509204000,
//       utc_offset: 7200000,
//       waitlist_count: 0,
//       yes_rsvp_count: 19,
//       venue: {
//         id: 26293604,
//         name: 'Chinese Tower',
//         lat: 48.15256118774414,
//         lon: 11.59210205078125,
//         repinned: false,
//         address_1: 'Englischer Garten 3',
//         city: 'München',
//         country: 'de',
//         localized_country_name: 'Germany',
//       },
//       group: {
//         created: 1469016785000,
//         name: 'Munich Kickball',
//         id: 20204783,
//         join_mode: 'open',
//         lat: 48.13999938964844,
//         lon: 11.579999923706055,
//         urlname: 'Munchen-Kickball',
//         who: 'Members',
//         localized_location: 'München, Germany',
//         state: '',
//         country: 'de',
//         region: 'en_US',
//         timezone: 'Europe/Berlin',
//       },
//       link: 'https://www.meetup.com/Munchen-Kickball/events/thdxzqyzjbvb/',
//       description: '<p>Hey neuer oder routinierter Kickball Player ;)</p> <p>Wir warten auf dich wie üblich um 13 Uhr an der südwestlichen Ecke des chinesischen Turms. Wir sind diejenigen mit dem roten Kickball-Ball:</p> <p>goo.gl/maps/Pqp9ecnv3Xx</p> <p>Wenn du ein bisschen später auftauchen kannst, komm einfach spontan auf das Fels. Es liegt etwas nördlich vom Chinesischen Turm:<br/>goo.gl/maps/DQjErwppk8z</p> <p>Fühl dich frei deine Freunde mitzubringen! Zusätzliche Spieler und neue Gesichter sind immer willkommen. Essen und Getränke kannst du gern mitbringen.</p> <p>Wir freuen uns, dich am Sonntag zu sehen!</p> <p>----------------------------</p> <p>Hey Gang!</p> <p>Feel free to bring blankets, drinks, and food if you like. Also feel free to bring friends! Extra players and new faces are always welcome.</p> <p>Meet at the Chinese Tower at 1 pm, southwest corner. We\'ll be the weirdos carrying the big red kickballs:</p> <p><a href=\'https://goo.gl/maps/Pqp9ecnv3Xx\' class=\'linkified\'>https://goo.gl/maps/Pqp9ecnv3Xx</a></p> <p>If you show up a bit late you can meet us at the field, which is a bit north of the Chinese Tower:</p> <p><a href=\'https://goo.gl/maps/DQjErwppk8z\' class=\'linkified\'>https://goo.gl/maps/DQjErwppk8z</a></p> <p>Looking forward to seeing you all on Sunday!</p> <p>- Scott</p> ',
//       visibility: 'public',
//     },
//     {
//       created: 1559417984000,
//       duration: 18000000,
//       id: '261960976',
//       name: 'Candlelight tales along the Isar',
//       date_in_series_pattern: false,
//       status: 'upcoming',
//       time: 1561136400000,
//       local_date: '2019-06-21',
//       local_time: '19:00',
//       rsvp_close_offset: 'PT144H',
//       updated: 1559417984000,
//       utc_offset: 7200000,
//       waitlist_count: 0,
//       yes_rsvp_count: 15,
//       venue: {
//         id: 26223377,
//         name: 'Gasthaus Alter Wirt',
//         lat: 48.10050582885742,
//         lon: 11.545145034790039,
//         repinned: false,
//         address_1: 'Fraunbergstraße 8',
//         city: 'München',
//         country: 'de',
//         localized_country_name: 'Germany',
//       },
//       group: {
//         created: 1423920004000,
//         name: 'Munich Explorers Club',
//         id: 18434240,
//         join_mode: 'open',
//         lat: 48.13999938964844,
//         lon: 11.579999923706055,
//         urlname: 'Munich-Explorers-Club',
//         who: 'Explorers',
//         localized_location: 'München, Germany',
//         state: '',
//         country: 'de',
//         region: 'en_US',
//         timezone: 'Europe/Berlin',
//       },
//       link: 'https://www.meetup.com/Munich-Explorers-Club/events/261960976/',
//       description: '<p>Dear all,</p> <p>It is with great pleasure that I come back to Munich to visit for a few days after a trip to the Faroe Islands!</p> <p>It would be great to see some old faces and new from the Munich Explorers Club. Let\'s plan an informal (and perhaps unusual) get-together for Friday, June 21, starting with dinner at the Gasthaus Alter Wirt in Thalkirchen. From there we can walk down to the Isar and stake out a spot along the riverbank just before dark. Bring your favorite personal travel or adventure story to tell, and we will take turns passing the candle (or flashlight). Feel free to bring blankets, drinks, etc.</p> <p>Hope to see you there!</p> <p>Steve</p> ',
//       visibility: 'public',
//     },
//     {
//       created: 1557561821000,
//       duration: 7200000,
//       id: 'hggczqyzjbmc',
//       name: 'Come run with the MH3!',
//       date_in_series_pattern: false,
//       status: 'upcoming',
//       time: 1561820400000,
//       local_date: '2019-06-29',
//       local_time: '17:00',
//       updated: 1557561821000,
//       utc_offset: 7200000,
//       waitlist_count: 0,
//       yes_rsvp_count: 2,
//       group: {
//         created: 1436202691000,
//         name: 'Munich Hash House Harriers',
//         id: 18722783,
//         join_mode: 'open',
//         lat: 48.13999938964844,
//         lon: 11.579999923706055,
//         urlname: 'Munich-Hash-House-Harriers',
//         who: 'Hashers and Harriettes',
//         localized_location: 'München, Germany',
//         state: '',
//         country: 'de',
//         region: 'en_US',
//         timezone: 'Europe/Berlin',
//       },
//       link: 'https://www.meetup.com/Munich-Hash-House-Harriers/events/hggczqyzjbmc/',
//       description: '<p>A trail is set by a \'hare\' usually in flour and/or chalk and then the \'pack\' has to try and find \'true trail\' at junctions. It is like a treasure hunt/ Schnitzel Lauf. The trails are therefore ideal for all levels of running with faster runners able to run more to check out the correct way and slower runners given the opportunity to catch up. We are not a road running group and our trails often take us into the forests or even off trail completely. It is a good way to get into fun running as it tends to be quite stop and go, rather than a continuous run.</p> <p>We are now on summer time. Don\'t forget to bring mozzie spray for the circle. There will be cars to store your bags.</p> <p>We\'ll post info here as it becomes available for the next run.</p> <p>You can also go to our regular website at <a href=\'http://www.munich-h3.eu \' class=\'linkified\'>http://www.munich-h3.eu</a></p> <p>or subscribe to the mailing list at [masked]</p> <p>We promise not to spam you. :-)</p> ',
//       how_to_find_us: 'To be decided',
//       visibility: 'public',
//     },
//     {
//       created: 1557561821000,
//       duration: 7200000,
//       id: 'hggczqyzkbrb',
//       name: 'Come run with the MH3!',
//       date_in_series_pattern: false,
//       status: 'upcoming',
//       time: 1563030000000,
//       local_date: '2019-07-13',
//       local_time: '17:00',
//       updated: 1557561821000,
//       utc_offset: 7200000,
//       waitlist_count: 0,
//       yes_rsvp_count: 2,
//       group: {
//         created: 1436202691000,
//         name: 'Munich Hash House Harriers',
//         id: 18722783,
//         join_mode: 'open',
//         lat: 48.13999938964844,
//         lon: 11.579999923706055,
//         urlname: 'Munich-Hash-House-Harriers',
//         who: 'Hashers and Harriettes',
//         localized_location: 'München, Germany',
//         state: '',
//         country: 'de',
//         region: 'en_US',
//         timezone: 'Europe/Berlin',
//       },
//       link: 'https://www.meetup.com/Munich-Hash-House-Harriers/events/hggczqyzkbrb/',
//       description: '<p>A trail is set by a \'hare\' usually in flour and/or chalk and then the \'pack\' has to try and find \'true trail\' at junctions. It is like a treasure hunt/ Schnitzel Lauf. The trails are therefore ideal for all levels of running with faster runners able to run more to check out the correct way and slower runners given the opportunity to catch up. We are not a road running group and our trails often take us into the forests or even off trail completely. It is a good way to get into fun running as it tends to be quite stop and go, rather than a continuous run.</p> <p>We are now on summer time. Don\'t forget to bring mozzie spray for the circle. There will be cars to store your bags.</p> <p>We\'ll post info here as it becomes available for the next run.</p> <p>You can also go to our regular website at <a href=\'http://www.munich-h3.eu \' class=\'linkified\'>http://www.munich-h3.eu</a></p> <p>or subscribe to the mailing list at [masked]</p> <p>We promise not to spam you. :-)</p> ',
//       how_to_find_us: 'To be decided',
//       visibility: 'public',
//     },
//     {
//       created: 1559597772000,
//       duration: 9000000,
//       id: '262016793',
//       name: 'Photo outing - Munich street scences',
//       date_in_series_pattern: false,
//       status: 'upcoming',
//       time: 1560587400000,
//       local_date: '2019-06-15',
//       local_time: '10:30',
//       updated: 1559597791000,
//       utc_offset: 7200000,
//       waitlist_count: 0,
//       yes_rsvp_count: 28,
//       venue: {
//         id: 26244972,
//         name: 'Fish\'s Fountain',
//         lat: 48.137245178222656,
//         lon: 11.576180458068848,
//         repinned: false,
//         address_1: 'Marienplatz',
//         city: 'München',
//         country: 'de',
//         localized_country_name: 'Germany',
//       },
//       group: {
//         created: 1500930561000,
//         name: 'Photography Workshops Munich',
//         id: 25119735,
//         join_mode: 'open',
//         lat: 48.13999938964844,
//         lon: 11.579999923706055,
//         urlname: 'Munchen-Photography-Workshops',
//         who: 'Members',
//         localized_location: 'München, Germany',
//         state: '',
//         country: 'de',
//         region: 'en_US',
//         timezone: 'Europe/Berlin',
//       },
//       link: 'https://www.meetup.com/Munchen-Photography-Workshops/events/262016793/',
//       description: '<p>Let\'s take photos of Munich\'s busy streets!</p> <p>We can share our thoughts about street-photography and practice a little taking photos of strangers in small groups.</p> <p>At the beginning, we will visit some touristic places such as the Viktualienmarkt, where people are used to being photographed. Once we have build up a little momentum and confidence in taking pictures of people on the street, we can venture to Karlsplatz and the Hauptbahnhof area to observe the different faces of Munich downtown!</p> <p>We will end at a cafe/restaurant and have a nice chat afterwards :)</p> ',
//       how_to_find_us: 'By the fountain at Marienplatz',
//       visibility: 'public',
//     },
//     {
//       created: 1559561039000,
//       duration: 10800000,
//       id: '261999193',
//       name: 'Make new friends! (21 to 45) - Meet ladies and gentlemen (Free Drink/Hosted)',
//       rsvp_limit: 90,
//       date_in_series_pattern: false,
//       status: 'upcoming',
//       time: 1560528000000,
//       local_date: '2019-06-14',
//       local_time: '18:00',
//       updated: 1559561039000,
//       utc_offset: 7200000,
//       waitlist_count: 0,
//       yes_rsvp_count: 70,
//       venue: {
//         id: 26202035,
//         name: '1912 Restaurant & Bar',
//         lat: 48.137569427490234,
//         lon: 11.559064865112305,
//         repinned: false,
//         address_1: 'Schwanthalerstraße 36',
//         city: 'München',
//         country: 'de',
//         localized_country_name: 'Germany',
//       },
//       group: {
//         created: 1465921965000,
//         name: 'The Expats Club of Munich (GERMANS welcome!) (2300+ expats)',
//         id: 20073299,
//         join_mode: 'open',
//         lat: 48.13999938964844,
//         lon: 11.579999923706055,
//         urlname: 'Munich-Expat-and-Internationals-Meetup',
//         who: 'Internationals',
//         localized_location: 'München, Germany',
//         state: '',
//         country: 'de',
//         region: 'en_US',
//         timezone: 'Europe/Berlin',
//       },
//       link: 'https://www.meetup.com/Munich-Expat-and-Internationals-Meetup/events/261999193/',
//       description: '<p>Please come and join us for a wonderful evening of making new friends with like minded ladies and gentlemen at the fabulous 1912 Restaurant &amp; Bar. You will be welcomed by your host Lydia and also be introduced to some of the other attendees. All our members also get exclusive FREE welcome drink. Join us and get started on making new connections and friendships!</p> <p>Our last social we had over 50 members present and this time wont be no different!</p> <p>Please click on the link below to purchase your ticket:<br/><a href=\'https://munich21to45.eventbrite.co.uk \'class=linkified>https://munich21to45.eventbrite.co.uk</a></p> <p>Have a look at photos from our recent meetups and see what you have been missing! <a href=\'http://bit.ly/MeetupPictures\' class=\'linkified\'>http://bit.ly/MeetupPictures</a></p> <p>Some Important Points:-</p> <p>- Our area is booked for MEETUP/LYDIA</p> <p>- This meetup is for members between the ages of 21 to 45 who want to make new friends in a safe and comfortable environment. Please come early to chat with members. You have no excuse to miss this event..!</p> <p>- FREE welcome drink for all our members!</p> <p>- Your host for the evening is LYDIA who will not only welcome you to our reserved area but also help you mix and mingle. No more nervousness, no awkward silences, no fiddling with your phone or staring into glasses. You will find yourself saying more hellos, shaking more hands and making more friends. Please come early as it is far easier to meet new people then. Please request LYDIA for help with introductions.</p> <p>-Please be aware that about 95% of those who attend come alone and about 75% are attending for the first time. You will not be alone. We know how you may feel and so LYDIA will take care of you.</p> <p>-Everyone attends these events to meet other members and so there is no reason to be shy or bashful. Also be aware that most people come alone. LYDIA is there to look after you and make you comfortable.</p> <p>-Please be aware that we are not a dating group. Our events are not organised to help your dating life or to make romantic matches. Our group is created to help ladies and gents meet other like minded ladies and gents and make new friends. This could be for singles or for those who are not single. Please do not attend our event if a perfect gender balance is important for your enjoyment of our meet-up</p> <p>------------------------------</p> <p>Event cost:</p> <p>Early Bird tickets - € 5 each<br/>Regular tickets - € 10 each<br/>(If you do not purchase tickets in advance but want to come then please show up on the day and give € 15 cash to LYDIA when you meet her)</p> <p>Please click on the link below to purchase your ticket:<br/><a href=\'https://munich21to45.eventbrite.co.uk\' class=\'linkified\'>https://munich21to45.eventbrite.co.uk</a></p> <p>------------------------<br/>This meetup is organised with www.connectwithlocals.com. Please watch the video below to see why you should attend our meetups.</p> <p><a href=\'http://bit.ly/whyattendoursocials \' class=linkified>http://bit.ly/whyattendoursocials</a></p> ',
//       how_to_find_us: 'Area reserved for Meetup/ LYDIA',
//       visibility: 'public',
//       pro_is_email_shared: false,
//     },
//     {
//       created: 1559634750000,
//       duration: 10800000,
//       id: '262027604',
//       name: 'Bank Holiday Party!(35 to 60) - Meet ladies and gentlemen (Free Drink/Hosted)',
//       rsvp_limit: 70,
//       date_in_series_pattern: false,
//       status: 'upcoming',
//       time: 1560960000000,
//       local_date: '2019-06-19',
//       local_time: '18:00',
//       updated: 1559634750000,
//       utc_offset: 7200000,
//       waitlist_count: 0,
//       yes_rsvp_count: 34,
//       venue: {
//         id: 26202035,
//         name: '1912 Restaurant & Bar',
//         lat: 48.137569427490234,
//         lon: 11.559064865112305,
//         repinned: false,
//         address_1: 'Schwanthalerstraße 36',
//         city: 'München',
//         country: 'de',
//         localized_country_name: 'Germany',
//       },
//       group: {
//         created: 1465921965000,
//         name: 'The Expats Club of Munich (GERMANS welcome!) (2300+ expats)',
//         id: 20073299,
//         join_mode: 'open',
//         lat: 48.13999938964844,
//         lon: 11.579999923706055,
//         urlname: 'Munich-Expat-and-Internationals-Meetup',
//         who: 'Internationals',
//         localized_location: 'München, Germany',
//         state: '',
//         country: 'de',
//         region: 'en_US',
//         timezone: 'Europe/Berlin',
//       },
//       link: 'https://www.meetup.com/Munich-Expat-and-Internationals-Meetup/events/262027604/',
//       description: '<p>If you do not have time to meet new friends over the week because your hectic work schedule, then we have the perfect social for you over an Bank Holiday!</p> <p>Please come and join us for a wonderful evening of making new friends with like minded ladies and gentlemen on a Bank Holiday at the fabulous 1912 Restaurant &amp; Bar. You will be welcomed by your host Lydia and also be introduced to some of the other attendees. All our members also get exclusive FREE welcome drink. Join us and get started on making new connections and friendships!</p> <p>Our last social we had over 40 members present and this time wont be no different!</p> <p>Please click on the link below to purchase your ticket:<br/><a href=\'https://bankholidaymunich.eventbrite.co.uk\' class=\'linkified\'>https://bankholidaymunich.eventbrite.co.uk</a></p> <p>Have a look at photos from our recent meetups and see what you have been missing! <a href=\'http://bit.ly/MeetupPictures\' class=\'linkified\'>http://bit.ly/MeetupPictures</a></p> <p>Some Important Points:-</p> <p>- Our area is booked for MEETUP/LYDIA</p> <p>- This meetup is for members between the ages of 35 to 60 who want to make new friends in a safe and comfortable environment. Please come early to chat with members. You have no excuse to miss this event..!</p> <p>- FREE welcome drink for all our members!</p> <p>- Your host for the evening is LYDIA who will not only welcome you to our reserved area but also help you mix and mingle. No more nervousness, no awkward silences, no fiddling with your phone or staring into glasses. You will find yourself saying more hellos, shaking more hands and making more friends. Please come early as it is far easier to meet new people then. Please request LYDIA for help with introductions.</p> <p>-Please be aware that about 95% of those who attend come alone and about 75% are attending for the first time. You will not be alone. We know how you may feel and so LYDIA will take care of you.</p> <p>-Everyone attends these events to meet other members and so there is no reason to be shy or bashful. Also be aware that most people come alone. LYDIA is there to look after you and make you comfortable.</p> <p>-Please be aware that we are not a dating group. Our events are not organised to help your dating life or to make romantic matches. Our group is created to help ladies and gents meet other like minded ladies and gents and make new friends. This could be for singles or for those who are not single. Please do not attend our event if a perfect gender balance is important for your enjoyment of our meet-up</p> <p>------------------------------</p> <p>Event cost:</p> <p>Early Bird tickets - € 5 each<br/>Regular tickets - € 10 each<br/>(If you do not purchase tickets in advance but want to come then please show up on the day and give € 15 cash to LYDIA when you meet her)</p> <p>Please click on the link below to purchase your ticket:<br/><a href=h\'ttps://bankholidaymunich.eventbrite.co.uk\' class=\'linkified\'>https://bankholidaymunich.eventbrite.co.uk</a></p> <p>------------------------<br/>This meetup is organised with www.connectwithlocals.com. Please watch the video below to see why you should attend our meetups.</p> <p><a href=\'http://bit.ly/whyattendoursocials\' class=\'linkified\'>http://bit.ly/whyattendoursocials</a></p> ',
//       how_to_find_us: 'Area reserved for Meetup/ LYDIA',
//       visibility: 'public',
//       pro_is_email_shared: false,
//     },
//     {
//       created: 1556734128000,
//       duration: 130500000,
//       id: '261079103',
//       name: 'Overnight Hike - Soiernumrundung: Schöttelkarspitze and Soiernspitze',
//       rsvp_limit: 10,
//       date_in_series_pattern: false,
//       status: 'upcoming',
//       time: 1561182300000,
//       local_date: '2019-06-22',
//       local_time: '07:45',
//       updated: 1559895497000,
//       utc_offset: 7200000,
//       waitlist_count: 20,
//       yes_rsvp_count: 9,
//       venue: {
//         id: 24847646,
//         name: 'Hauptbahnhof',
//         lat: 48.14134216308594,
//         lon: 11.557599067687988,
//         repinned: true,
//         address_1: 'Hauptbahnhof',
//         city: 'München',
//         country: 'de',
//         localized_country_name: 'Germany',
//       },
//       group: {
//         created: 1524419703000,
//         name: 'Munich International Hiking',
//         id: 28247630,
//         join_mode: 'open',
//         lat: 48.13999938964844,
//         lon: 11.579999923706055,
//         urlname: 'Munich-International-Hiking',
//         who: 'Members',
//         localized_location: 'München, Germany',
//         state: '',
//         country: 'de',
//         region: 'en_US',
//         timezone: 'Europe/Berlin',
//       },
//       link: 'https://www.meetup.com/Munich-International-Hiking/events/261079103/',
//       description: '<p>Soiernhaus is our destination in June. We will hike up two of Karwendel\'s most famous peaks: Schöttelkarspitze and Soiernspitze. Both days require previous hiking experience, a head for heights, and proper hiking boots. Strictly no trainers or mid-height footwear. I\'m kindly asking First Timers to join at least two medium to difficult day hikes before coming on this overnight hike. Thank you.</p> <p>ROUTE</p> <p>Day 1 - Saturday 22/06/2019<br/>Krün (850m) - Schwarzkopf (1150m) - Seinskopf (1961m) - Schöttelkarspitze (2050m) - Soiernhaus and Soiernsee (1600m). Walking time = ~5h, distance = 11km, elevation gain = 1250hm. This is a medium hike. Please bring a packed lunch along.</p> <p>A sheet sleeper is required to spend the night at Soiernhaus. I booked 10x Matratzenlager for us.</p> <p>Day 2 - Sunday 23/06/2019<br/>Soiernhaus (1600m) - Schöttelkarspitze (2050m) – Reißende Lahnspitze (2170m) – Soiernspitze (2253m) - Soiernhaus (1600m) - Fischbachalm (1400m) - Krün (850m). Walking time = ~8h, distance = 19km, elevation gain = 900hm. This is a difficult hike. We will have lunch at Soiernhaus before we hike back to Krün.</p> <p>COST ESTIMATE</p> <p>- €20 night at Soiernhaus (€10 for DAV members)<br/>- €30 share of train and bus ticket (price of the train ticket will be split evenly between the group)<br/>- A deposit of €20 (€10 for DAV members) is required to secure your spot<br/>- I\'d strongly recommend to bring ~€100 of cash along to pay for your lunch, dinner, and breakfast</p> <p>Please transfer the deposit by Friday 07/06/2019 to secure your spot. You can pay by PayPal or bank transfer (please send me a PM). Please select “private” when paying by PayPal otherwise I’ll be charged a fee of €1.50.</p> <p><a href=\'http://paypal.me/sarahdheldt\' class=\'linkified\'>http://paypal.me/sarahdheldt</a></p> <p>The organiser has to pay a deposit for all ten beds when booking. Most mountain huts don\'t offer a refund if the booking is cancelled less than a week before the booking. Therefore your deposit is not refundable, either.</p> <p>MEETING POINT</p> <p>München Hbf, next to Radius Tours, 07:45am on Saturday 22.June.2018, our train leaves at 07:59.<br/>Return to Munich: Sunday 23.June.2019 ~ 8pm-ish</p> <p>--<br/><a href=\'http://www.sektion-hochland.de/soiernhaus/index.php?id=soiernhaus\' class=\'linkified\'>http://www.sektion-hochland.de/soiernhaus/index.php?id=soiernhaus</a></p> ',
//       how_to_find_us: 'Next to Radius Tours',
//       visibility: 'public',
//     },
//     {
//       created: 1559143189000,
//       duration: 7200000,
//       id: '261866107',
//       name: 'Happiness Club ',
//       rsvp_limit: 15,
//       date_in_series_pattern: false,
//       status: 'upcoming',
//       time: 1561190400000,
//       local_date: '2019-06-22',
//       local_time: '10:00',
//       updated: 1559143189000,
//       utc_offset: 7200000,
//       waitlist_count: 0,
//       yes_rsvp_count: 10,
//       venue: {
//         id: 26065554,
//         name: 'Café Katzentempel',
//         lat: 48.14914321899414,
//         lon: 11.575069427490234,
//         repinned: true,
//         address_1: 'Türkenstraße 29',
//         city: 'München',
//         country: 'de',
//         localized_country_name: 'Germany',
//       },
//       group: {
//         created: 1454229357000,
//         name: 'München Women\'s Sport, Well-being and Happiness',
//         id: 19472511,
//         join_mode: 'open',
//         lat: 48.13999938964844,
//         lon: 11.579999923706055,
//         urlname: 'Munchen-Womens-Sport-Well-being-and-Happiness',
//         who: 'Members',
//         localized_location: 'München, Germany',
//         state: '',
//         country: 'de',
//         region: 'en_US',
//         timezone: 'Europe/Berlin',
//       },
//       link: 'https://www.meetup.com/Munchen-Womens-Sport-Well-being-and-Happiness/events/261866107/',
//       description: '<p>Join me, the cats and other like minded women for brunch and discussion on this month\'s topic related to happiness.</p> <p>Following on from May\'s topic of RESILIENCE and the ability to bounce back when life is difficult, we will discuss SELF COMPASSION and being kinder to ourselves.</p> <p>The event is in ENGLISH and is FREE but please support the Cat Cafe by purchasing food and drinks. Thank you.</p> ',
//       how_to_find_us: 'Table booked under Julie/Happiness Club',
//       visibility: 'public',
//     },
//     {
//       created: 1557840085000,
//       duration: 5400000,
//       id: '261449343',
//       name: 'Fotowalk vom Hofgarten in den Englischen Garten',
//       date_in_series_pattern: false,
//       status: 'upcoming',
//       time: 1561566600000,
//       local_date: '2019-06-26',
//       local_time: '18:30',
//       updated: 1557840195000,
//       utc_offset: 7200000,
//       waitlist_count: 0,
//       yes_rsvp_count: 26,
//       venue: {
//         id: 26382269,
//         name: 'Hofgarten',
//         lat: 48.14277648925781,
//         lon: 11.579999923706055,
//         repinned: false,
//         address_1: 'Hofgartenstraße 1',
//         city: 'München',
//         country: 'de',
//         localized_country_name: 'Germany',
//       },
//       group: {
//         created: 1517292755000,
//         name: 'Smartphone-Fotografie in München',
//         id: 27321953,
//         join_mode: 'open',
//         lat: 48.13999938964844,
//         lon: 11.579999923706055,
//         urlname: 'Smartphone-Fotografie-in-Munchen',
//         who: 'Mitglieder',
//         localized_location: 'München, Germany',
//         state: '',
//         country: 'de',
//         region: 'en_US',
//         timezone: 'Europe/Berlin',
//       },
//       link: 'https://www.meetup.com/Smartphone-Fotografie-in-Munchen/events/261449343/',
//       description: '<p>Beim letzten Fotowalk haben wir beschlossen, uns das nächste Mal im Hofgarten zu treffen.</p> <p>Wir treffen uns am Pavillion im Hofgarten um 18:30 Uhr, fotografieren dann dort ein bisschen und laufen dann bis zum Chinesischen Turm im Englischen Garten. Ende Juni ist hoffentlich so gutes Wetter, dass wir dort noch zusammen im Biergarten sitzen können.</p> <p>Wie immer geht es uns beim Fotowalk um den Austausch, das gemeinsame Fotografieren, das Entdecken von tollen Motiven in der Gruppe.</p> <p>Wir freuen uns auf einen schönen Walk,<br/>Simone und Mona</p> ',
//       visibility: 'public',
//     },
//     {
//       created: 1558984782000,
//       duration: 25200000,
//       id: '261811924',
//       name: 'Infostand Promenadenfest',
//       date_in_series_pattern: false,
//       status: 'upcoming',
//       time: 1561809600000,
//       local_date: '2019-06-29',
//       local_time: '14:00',
//       updated: 1558984782000,
//       utc_offset: 7200000,
//       waitlist_count: 0,
//       yes_rsvp_count: 1,
//       group: {
//         created: 1553170999000,
//         name: 'München Riemer Park run',
//         id: 31442178,
//         join_mode: 'open',
//         lat: 48.13999938964844,
//         lon: 11.579999923706055,
//         urlname: 'Munchen-Riemer-Park-run',
//         who: 'Members',
//         localized_location: 'München, Germany',
//         state: '',
//         country: 'de',
//         region: 'en_US',
//         timezone: 'Europe/Berlin',
//       },
//       link: 'https://www.meetup.com/Munchen-Riemer-Park-run/events/261811924/',
//       description: '<p>Hallo Leute,</p> <p>Wir möchten den Münchnen Riemer Park parkrun auf dem Promenadenfest <a href=\'https://www.promenadenfest.com/ \' class=\'linkified\'>https://www.promenadenfest.com/</a> den Bewohnern der Messestadt und Umgebung mit einem Infostand vorstellen. Hierzu werden noch Helfer gesucht.<br/>Aufbau ist ab 11:00 möglich.<br/>Der Stand sollte von 15:00 bis ca. 21:00 Uhr besetzt sein und es sollte immer jemand anwesend sein, der Deutsch kann.<br/>Wer kann helfen?</p> <p>Vielen Dank und Grüße<br/>Michael Tel. [masked]</p> ',
//       visibility: 'public',
//     },
//   ],
// };

// export { mockEvents };


